name: AltumGaxiqMC
version: 1.0.0
main: ru.altum.altumgaxiqmc.AltumGaxiqMC
api-version: "1.21"
authors: [Altum]
softdepend: [PlaceholderAPI, floodgate]

commands:
  gm:
    description: Быстрая смена режима игры
    usage: /gm <c|s|a|sp|creative|survival|adventure|spectator> [ник]
    aliases: [gamemode]

permissions:
  altumgaxiq.gm:
    default: op
  altumgaxiq.gm.others:
    default: op
